[workspace]
members = ["crates/gslm-core", "packages/gslm"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/gn00678465/google-sheet-languages-model"

[workspace.dependencies]
gslm-core = { path = "crates/gslm-core" }
serde_json = { version = "1", features = ["preserve_order"] }
indexmap = { version = "2", features = ["serde"] }
thiserror = "2"
napi = { version = "3", default-features = false, features = ["napi8", "serde-json-ordered", "object_indexmap"] }
napi-derive = { version = "3", default-features = false, features = ["type-def"] }
napi-build = "2"

[profile.release]
codegen-units = 1
lto = true
strip = "symbols"
