/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Reads and writes whole Tabs of a Google Sheet. */
export declare class SheetsClient {
  /**
   * Create a client. Credentials are validated here (file readable,
   * JSON is a service-account key); no token is exchanged yet.
   */
  static create(options?: SheetsClientOptions | undefined | null): Promise<SheetsClient>
  /**
   * Create a client from a Target returned by `loadConfig`. The
   * process-local opaque handle keeps credential JSON inside Rust.
   */
  static fromConfig(target: ConfigTargetForClient): Promise<SheetsClient>
  /**
   * Read the whole tab as rows of strings (header row first). Feed the
   * result to `sheetToModel`.
   */
  readTab(sheetId: string, tab: string): Promise<Array<Array<string>>>
  /**
   * Replace the tab's content with `rows` (clear, then write from A1 with
   * RAW input). Use `modelToSheet` to build `rows`.
   */
  writeTab(sheetId: string, tab: string, rows: Array<Array<string>>): Promise<void>
}

/** Safe credential metadata. It never contains credential JSON. */
export interface ConfigCredentials {
  kind: string
  path?: string
  env?: string
}

/** CLI-style overrides with the same precedence and validation as `GSLM_*`. */
export interface ConfigOverrides {
  sheet?: string
  tab?: string
  locales?: Array<string>
  path?: string
  format?: string
  keySeparator?: string
  credentials?: string
  credentialsJson?: string
}

/** JSON Schema draft 2020-12 generated from the Rust raw-config types. */
export declare function configSchema(): any

/** A Target ready for pull or push. `path` is an absolute template. */
export interface ConfigTarget {
  name: string
  sheet: string
  tab: string
  locales: Array<string>
  path: string
  format: string
  keySeparator: string
  credentials: ConfigCredentials
  /**
   * Opaque, process-local handle used by [`SheetsClient::from_config`]. It
   * contains no credential data, but must be retained with this Target.
   */
  credentialHandle: string
}

/**
 * Internal input for `SheetsClient.fromConfig`. It deliberately contains
 * only the opaque credential handle returned by `loadConfig`.
 */
export interface ConfigTargetForClient {
  credentialHandle: string
}

/**
 * How to authenticate. Provide at most one field; omit all for Google
 * Application Default Credentials.
 */
export interface CredentialsOptions {
  /** Path to a service-account JSON key file. */
  file?: string
  /** Contents of a service-account JSON key. */
  json?: string
  /** An already-obtained OAuth2 access token (never refreshed). */
  accessToken?: string
}

/**
 * Flatten a nested catalog object into a single-level object whose keys are
 * joined by `separator` (default `"."`). Key order is preserved.
 *
 * Throws if the input is not a plain object, if any key segment is a number,
 * or if `separator` is empty.
 */
export declare function flatten(value: any, separator?: string | undefined | null): Record<string, any>

/** Controls a high-level pull call from JavaScript. */
export interface HighLevelPullOptions {
  dryRun?: boolean
  force?: boolean
  /** Test/embedding-only Sheets origin; production callers omit it. */
  baseUrl?: string
  /** Test/embedding-only static token; production callers omit it. */
  accessToken?: string
}

/** Controls a high-level push call from JavaScript. */
export interface HighLevelPushOptions {
  dryRun?: boolean
  force?: boolean
  strict?: boolean
  /** Test/embedding-only Sheets origin; production callers omit it. */
  baseUrl?: string
  /** Test/embedding-only static token; production callers omit it. */
  accessToken?: string
}

/** A Catalog file affected by pull. */
export interface JsFileSummary {
  locale: string
  path: string
  keys: number
  outcome?: string
}

/** One Locale's key count in a push result. */
export interface JsLocaleKeyCount {
  locale: string
  keys: number
}

/** Data-only summary returned by a high-level pull. */
export interface JsPullSummary {
  target: string
  files: Array<JsFileSummary>
  created: number
  updated: number
  unchanged: number
}

/** Data-only summary returned by a high-level push. */
export interface JsPushSummary {
  target: string
  rows: number
  columns: number
  localeKeys: Array<JsLocaleKeyCount>
  orphanKeys: Array<string>
  warnings: Array<string>
}

/** Fully resolved config data that is safe to serialize or print. */
export interface JsResolvedConfig {
  configPath?: string
  targets: Array<ConfigTarget>
  warnings: Array<string>
}

/**
 * Discover and load the config synchronously. File I/O is intentionally
 * small, and all errors carry a stable `[CONFIG_*]` prefix for `index.js`.
 */
export declare function loadConfig(options?: LoadConfigOptions | undefined | null): JsResolvedConfig

/**
 * Options accepted by [`load_config`]. `env` is mainly useful for tests and
 * embedded callers that need an isolated process environment.
 */
export interface LoadConfigOptions {
  cwd?: string
  configPath?: string
  env?: Record<string, string>
  overrides?: ConfigOverrides
  targets?: Array<string>
  loadDotenv?: boolean
}

/**
 * A Model as plain data: an ordered list of locales (the first is the Source
 * locale) and one flat catalog per locale. Serializable as JSON.
 */
export interface Model {
  locales: Array<string>
  /**
   * `locale → (key → translation)`. Missing keys mean "not translated";
   * empty strings are kept as-is.
   */
  catalogs: Record<string, Record<string, string>>
}

/**
 * Build Tab rows from a Model: header `["key", ...locales]`, then one row
 * per key in Source-locale order followed by keys that exist only in other
 * locales. Missing translations and empty strings both become `""`.
 */
export declare function modelToSheet(model: Model): Array<Array<string>>

/**
 * Keys that exist in some non-Source locale but not in the Source locale,
 * in the order `modelToSheet` appends them.
 */
export declare function orphanKeys(model: Model): Array<string>

/**
 * Pull one Target returned by `loadConfig` without reparsing environment
 * credentials. The hidden credential handle remains entirely in Rust.
 */
export declare function pull(target: ConfigTarget, options?: HighLevelPullOptions | undefined | null): Promise<JsPullSummary>

/**
 * Push one Target returned by `loadConfig` without reparsing environment
 * credentials. The hidden credential handle remains entirely in Rust.
 */
export declare function push(target: ConfigTarget, options?: HighLevelPushOptions | undefined | null): Promise<JsPushSummary>

/**
 * Drop credentials once JavaScript no longer retains the Target that owns
 * this opaque handle. Unknown handles are intentionally harmless.
 */
export declare function releaseConfigCredentials(handle: string): void

/**
 * Run the same clap-driven CLI as `bin/gslm.js`, returning its shell exit
 * code instead of throwing command errors.
 */
export declare function runCli(argv: Array<string>, options?: RunCliOptions | undefined | null): Promise<number>

/** Options for an embedded CLI invocation. */
export interface RunCliOptions {
  cwd?: string
  isTty?: boolean
  color?: string
  /** Explicit Sheets origin for embedding hosts and tests. */
  baseUrl?: string
  /** Explicit static token for embedding hosts and tests. */
  accessToken?: string
}

export interface SheetsClientOptions {
  credentials?: CredentialsOptions
  /**
   * Override the Sheets API origin (tests / proxies).
   * Default `https://sheets.googleapis.com`.
   */
  baseUrl?: string
}

/**
 * Parse Tab rows (first row = header: key column + locale columns) into a
 * Model for the requested locales. Columns are matched by header text; the
 * first column is always the key column. Empty cells are missing
 * translations; rows with an empty key are skipped.
 *
 * Throws if the sheet is empty, a requested locale is not in the header, or a
 * key appears twice.
 */
export declare function sheetToModel(rows: Array<Array<string>>, locales: Array<string>): Model

/**
 * Inverse of `flatten`: rebuild a nested object from dotted keys.
 * Key order is preserved at every level.
 *
 * Throws on numeric key segments, on conflicts such as `a` together with
 * `a.b`, or if `separator` is empty.
 */
export declare function unflatten(flat: Record<string, any>, separator?: string | undefined | null): any

/**
 * Version of the installed gslm package (read from package.json at build
 * time, so it always matches what `npm install` resolved).
 */
export declare function version(): string
