/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Flatten a nested catalog object into a single-level object whose keys are
 * joined by `separator` (default `"."`). Key order is preserved.
 *
 * Throws if the input is not a plain object, if any key segment is a number,
 * or if `separator` is empty.
 */
export declare function flatten(value: any, separator?: string | undefined | null): Record<string, any>

/**
 * Version of the installed gslm package (read from package.json at build
 * time, so it always matches what `npm install` resolved).
 */
export declare function version(): string
